swagger: "2.0"
info:
  version: "0.0.1"
  title: BaiXiaoSheng - A mointor for DevOps
# during dev, should point to your local machine
host: localhost:10010
# basePath prefixes all resource paths
basePath: /api
schemes:
  # tip: remove http to make production-grade
  - http
  - https
consumes:
  - application/json
produces:
  - application/json
  - text/plain
paths:
  /links:
    x-swagger-router-controller: links
    get:
      description: Return all the links under monitor
      operationId: getLinks
      responses:
        200:
          description: Success
          schema:
            $ref: "#/definitions/Link"
    post:
      description: Create a new Link to be monitored
      operationId: create
      parameters:
        - name: link
          in: body
          schema:
            $ref: "#/definitions/Link"
      responses:
        201:
          description: Success
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /hello:
    x-swagger-router-controller: hello_world
    get:
      description: Returns 'Hello' to the caller
      operationId: hello
      parameters:
        - name: name
          in: query
          description: The name of the person to whom to say hello
          required: false
          type: string
      responses:
        200:
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/HelloWorldResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
# complex objects have schema definitions
definitions:
  Link:
    required:
      - url
    properties:
      url:
        type: string
      satus:
        type: integer
      description:
        type: string
  HelloWorldResponse:
    required:
      - message
    properties:
      message:
        type: string
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
