swagger: "2.0"
info:
  version: "0.0.1"
  title: BaiXiaoSheng - A mointor for DevOps
# during dev, should point to your local machine
host: localhost:10010
# basePath prefixes all resource paths
basePath: /api
schemes:
  # tip: remove http to make production-grade
  - http
  - https
consumes:
  - application/json
produces:
  - application/json
  - text/plain
  - text/html
paths:
  /links:
    x-swagger-router-controller: links
    get:
      description: Return all the links under monitor
      operationId: getLinks
      responses:
        default:
          description: Return all the links
          schema:
            type: string
    post:
      description: Create a new Link to be monitored
      operationId: create
      parameters:
        - name: link
          in: body
          schema:
            $ref: "#/definitions/Link"
      responses:
        201:
          description: Success
          schema:
            type: string
        default:
          description: Error
          schema:
            type: string
  /vmhosts:
    x-swagger-router-controller: vmhosts
    get:
      description: Return all the vmm hosts and vm hosts
      operationId: getVmHosts
      responses:
        200:
          description: Return all the vmm hosts and vm hosts
          schema:
            $ref: "#/definitions/VmHosts"
  /vm_search:
    x-swagger-router-controller: vmhosts
    get:
      description: Return all the vmm hosts and vm hosts that matched by the word
      operationId: search
      parameters:
        - name: q
          in: query
          description: The word that would like to search
          required: true
          type: string
      responses:
        default:
          description: Return all the vmm hosts and vm hosts that matched by the word
          schema:
            $ref: "#/definitions/VmHosts"
# complex objects have schema definitions
definitions:
  Link:
    required:
      - url
    properties:
      url:
        type: string
      proxy:
        type: string
      satus:
        type: integer
      lastResTime:
        type: integer
      avgResTime:
        type: integer
      description:
        type: string
  HelloWorldResponse:
    required:
      - message
    properties:
      message:
        type: string
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
  VmHosts:
    required:
      - ip
      - hostname
      - domain
      - has_problems
    properties:
      ip:
        type: string
      hostname:
        type: string
      has_problems:
        type: string
      domain:
        type: array
        items:
          $ref: "#/definitions/Guest"
  Guest:
    properties:
      uuid:
        type: string
      hostname:
        type: string
      mac:
        type: string
      ip:
        type: string
      domain:
        type: string
