swagger: "2.0"
info:
  version: "0.0.1"
  title: BaiXiaoSheng - A mointor for DevOps
# during dev, should point to your local machine
host: localhost:10010
# basePath prefixes all resource paths
basePath: /api
schemes:
  # tip: remove http to make production-grade
  - http
  - https
consumes:
  - application/json
produces:
  - application/json
  - text/plain
  - text/html

paths:
  /hosts:
    x-swagger-router-controller: hosts
    get:
      description: "To return all the grouped hosts, intended to be used by ansible-playbook"
      operationId: list
      responses:
        default:
          description: Return a json representation of multiple groups of hosts
          schema:
            type: string
  /links:
    x-swagger-router-controller: links
    get:
      description: Return all the links under monitor
      operationId: getLinks
      responses:
        default:
          description: Return all the links
          schema:
            type: string
    post:
      description: Create a new Link to be monitored
      operationId: create
      parameters:
        - name: link
          in: body
          schema:
            $ref: "#/definitions/Link"
      responses:
        201:
          description: Success
          schema:
            required:
              - key
              - value
            properties:
              key:
                type: string
              value:
                $ref: "#/definitions/Link"

        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /links/{id}:
    x-swagger-router-controller: links
    delete:
      operationId: del
      parameters:
        - name: id
          required: true
          type: string
          in: path
      responses:
        default:
          description: Array of links left
          schema:
            type: string
  /vmhosts:
    x-swagger-router-controller: vmhosts
    get:
      description: Return all the vmm hosts and vm hosts
      operationId: getVmHosts
      responses:
        200:
          description: Return all the vmm hosts and vm hosts
          schema:
            $ref: "#/definitions/VmHosts"
  /vmhosts/{location}:
    x-swagger-router-controller: vmhosts
    get:
      description: To Return all the vmm hosts and vm hosts belongs to the location
      operationId: getVmHosts
      parameters:
        - name: location
          required: true
          type: string
          in: path
      responses:
        200:
          description: Return all the vmm hosts and vm hosts belongs to the location
          schema:
            $ref: "#/definitions/VmHosts"
  /vm_counter:
    x-swagger-router-controller: vmhosts
    get:
      description: Return statistic of vm hosts last week
      operationId: stat
      responses:
        default:
          description: Return statistic of vm hosts last week
          schema:
            $ref: "#/definitions/VmStat"
    post:
      description: Counter vm hosts
      operationId: counter
      responses:
        201:
          description: Success
          schema:
            type: string
  /vm_search:
    x-swagger-router-controller: vmhosts
    get:
      description: Return all the vmm hosts and vm hosts that matched by the word
      operationId: search
      parameters:
        - name: q
          in: query
          description: The word that would like to search
          required: true
          type: string
      responses:
        default:
          description: Return all the vmm hosts and vm hosts that matched by the word
          schema:
            $ref: "#/definitions/VmHosts"
  /benchs:
    x-swagger-router-controller: benchs
    get:
      description: Return all the benchs
      operationId: benchs
      responses:
        200:
          description: Return all the benchs
          schema:
            $ref: "#/definitions/Benchs"
    put:
      description: Mark host has problem
      operationId: create
      parameters:
        - name: bench
          in: body
          schema:
            $ref: "#/definitions/Benchs"
      responses:
        201:
          description: Success
          schema:
            $ref: "#/definitions/Benchs"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
    delete:
      description: Release host who has been marked
      operationId: del
      parameters:
        - name: bench
          in: body
          schema:
            $ref: "#/definitions/Benchs"
      responses:
        default:
          description: Array of benchs left
          schema:
            $ref: "#/definitions/Benchs"
  /events:
    x-swagger-router-controller: benchs
    get:
      operationId: events
      responses:
        default:
          description: Array of current events in Zabbix
          schema:
            type: string
  /history:
    x-swagger-router-controller: benchs
    get:
      description: Return all history of benchs during several days
      operationId: history
      parameters:
        - name: start
          in: query
          type: string
        - name: end
          in: query
          type: string
      responses:
        default:
          description: Array of history
          schema:
            $ref: "#/definitions/Benchs"
  /dashboard/mttr:
    x-swagger-router-controller: dashboard
    get:
      description: Return all mttr during seven days
      operationId: mttr
      responses:
        default:
          description: Object of mttr
          schema:
            $ref: "#/definitions/Mttr"

# complex objects have schema definitions
definitions:
  Link:
    required:
      - url
    properties:
      url:
        type: string
        pattern: "https?:\/\/.+"
      proxy:
        type: string
      satus:
        type: integer
      lastResTime:
        type: integer
      avgResTime:
        type: integer
      description:
        type: string
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
  VmHosts:
    required:
      - ip
      - hostname
      - domain
      - has_problems
    properties:
      ip:
        type: string
      hostname:
        type: string
      has_problems:
        type: string
      domain:
        type: array
        items:
          $ref: "#/definitions/Guest"
  Guest:
    properties:
      uuid:
        type: string
      hostname:
        type: string
      mac:
        type: string
      ip:
        type: string
      domain:
        type: string
  Benchs:
    properties:
      ip:
        type: string
      hostname:
        type: string
      markedAt:
        type: string
      releaseAt:
        type: string
  Mttr:
    properties:
      project:
        type: string
      hosts:
        description: total number of hosts
        type: integer
      mttr:
        type: integer
      rate:
        type: number
  VmStat:
    properties:
      total:
        type: integer
      current:
        type: integer
      stats:
        type: array
        items:
          $ref: "#/definitions/Stats"
  Stats:
    properties:
      day:
        type: string
      count:
        type: integer
